# Site wide configuration

title:            CPrograming
locale:           en_US
url:              ""
#url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
markdown_ext:  markdown,mkd,mkdn,md
#highlighter: pygments

sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

# maruku:
#   use_tex:    false
#   use_divs:   false

# Site owner
owner:
  name: vanCopper
  avatar: van.jpg
  bio: "Try Your Best."
  email: vancopperm@gmail.com
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: vanCopper
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
